version: '3.7'
services:
        db:
                image: mysql:8.0.15
                volumes:
                        # Keep a local copy of the data.
                        - ./tmp/mysq:/var/lib/mysql
                        # Run migration files when starting the container.
                        - ./migrations:/docker-entrypoint-initdb.d
                command: --default-authentication-plugin=mysql_native_password
                ports:
                        - $DB_HOST:3306:3306
                env_file:
                        .env
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_USER: $DB_USER
                        MYSQL_PASSWORD: $DB_PASS
                        MYSQL_DATABASE: $DB_NAME

        app:
                image: $NAME
                build:
                        context: .
                        labels:
                                org.label-schema.build-date: $BUILD_DATE
                                org.label-schema.name: $NAME
                                org.label-schema.description: $DESCRIPTION 
                                org.label-schema.url: $URL
                                org.label-schema.vcs-url: $VCS_URL
                                org.label-schema.vcs-ref: $VCS_REF 
                                org.label-schema.vendor: $VENDOR 
                                org.label-schema.version: $VERSION
                                org.label-schema.docker.schema-version: "1.0"
                                org.label-schema.docker.cmd: $CMD

